import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { formatCurrency, formatNumber } from '@/lib/format'
import { PageHeader } from '@/components/app/page-header'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

function sum(rows:any[]|null|undefined,key:string){return(rows??[]).reduce((t,r)=>t+Number(r?.[key]??0),0)}
export default async function ReportsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const sp=await searchParams; const raw=Array.isArray(sp.month)?sp.month[0]:sp.month; const now=new Date(); const month=raw&&/^\d{4}-\d{2}$/.test(raw)?raw:now.toISOString().slice(0,7); const [y,m]=month.split('-').map(Number); const start=new Date(Date.UTC(y,m-1,1)).toISOString(); const end=new Date(Date.UTC(y,m,1)).toISOString();
 const supabase=await createClient(); const [{data:invoices},{data:expenses},{data:orders}]=await Promise.all([supabase.from('invoices').select('total,paid_amount,status').gte('issued_at',start).lt('issued_at',end),supabase.from('expenses').select('amount').gte('expense_date',month+'-01').lt('expense_date',new Date(Date.UTC(y,m,1)).toISOString().slice(0,10)),supabase.from('work_orders').select('status').gte('opened_at',start).lt('opened_at',end)]);
 const invoiceTotal=sum(invoices,'total'),paidTotal=sum(invoices,'paid_amount'),expenseTotal=sum(expenses,'amount'),outstanding=Math.max(0,invoiceTotal-paidTotal); const completed=(orders??[]).filter(o=>o.status==='completed'||o.status==='delivered').length; const open=Math.max(0,(orders?.length??0)-completed);
 const cards=[['إجمالي الفواتير',formatCurrency(invoiceTotal)],['المحصل',formatCurrency(paidTotal)],['المتبقي',formatCurrency(outstanding)],['إجمالي المصروفات',formatCurrency(expenseTotal)],['صافي بعد المصروفات',formatCurrency(paidTotal-expenseTotal)],['أوامر مكتملة',formatNumber(completed)],['أوامر مفتوحة',formatNumber(open)]];
 return <div className="mx-auto flex max-w-7xl flex-col gap-6"><PageHeader title="التقارير" description="تقارير شهرية مالية وتشغيلية بالجنيه المصري"/><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-md border bg-card px-3 py-2">الشهر المحدد: {month}</span><Link href="/reports" className="rounded-md border px-3 py-2">الشهر الحالي</Link>{[-1,0,1].map(i=>{const d=new Date(Date.UTC(y,m-1+i,1));const v=d.toISOString().slice(0,7);return <Link key={v} href={'/reports?month='+v} className="rounded-md border px-3 py-2">{v}</Link>})}</div><section className="grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(([t,v])=><Card key={t}><CardHeader><CardTitle className="text-sm text-muted-foreground">{t}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{v}</p></CardContent></Card>)}</section><Card><CardHeader><CardTitle>ملخص الشهر</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">جميع القيم المالية بالجنيه المصري، والحسابات مقتصرة على الشهر المحدد.</CardContent></Card></div>
}
